// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnh1vxPxLMhg4p4v-EdSm2Op2P8rWC89w',
    appId: '1:546711642853:web:b06cf064c5a275a4a2ea0c',
    messagingSenderId: '546711642853',
    projectId: 'moneymanager-769de',
    authDomain: 'moneymanager-769de.firebaseapp.com',
    storageBucket: 'moneymanager-769de.appspot.com',
    measurementId: 'G-C2BSHMGLFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACIXvOffSGV1D0rtAmyAbeig-MFcEScH0',
    appId: '1:546711642853:android:a895481120613435a2ea0c',
    messagingSenderId: '546711642853',
    projectId: 'moneymanager-769de',
    storageBucket: 'moneymanager-769de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWlStAR5mA8XkfFhZlUvA4UvAK2tJfJBY',
    appId: '1:546711642853:ios:7351dc90f8cd08fba2ea0c',
    messagingSenderId: '546711642853',
    projectId: 'moneymanager-769de',
    storageBucket: 'moneymanager-769de.appspot.com',
    iosClientId: '546711642853-ban847t44q0gme6tpgfjc1qav7lj5osa.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneymanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWlStAR5mA8XkfFhZlUvA4UvAK2tJfJBY',
    appId: '1:546711642853:ios:7351dc90f8cd08fba2ea0c',
    messagingSenderId: '546711642853',
    projectId: 'moneymanager-769de',
    storageBucket: 'moneymanager-769de.appspot.com',
    iosClientId: '546711642853-ban847t44q0gme6tpgfjc1qav7lj5osa.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneymanager',
  );
}
